domain: hbr.org
extraction:
  article_content:
    selector: article .article-body__content
    fallback: article
    exclude_selectors:
    - nav
    - header
    - footer
    - .w-dyn-list
    - .w-dyn-items
    - '[class*=''collection-list'']'
    - '[class*=''share'']'
    - '[class*=''social'']'
    - '[class*=''recommended'']'
    - '[class*=''related'']'
    - '[class*=''promo'']'
    - '[class*=''ad'']'
    - '[class*=''newsletter'']'
    - '[class*=''signup'']'
    - '[class*=''subscribe'']'
    - '[class*=''cta'']'
    - '[aria-label*=''Share'']'
    - '[aria-label*=''Post'']'
    - '[role=''complementary'']'
    - aside
    - .article-actions
    - .about-the-author-section
    - .related-articles-section
    - .citation-wrapper
    - .comments-section
    - .comments
    - .topics-list
    - .article-meta__footer
    - .feedback-form
    - '[itemtype*=''WebPageElement''][itemprop=''author'']'
    - .user-feedback
    - .hbr-store-callout
    - '[class*=''PrintLogo_print-logo'']'
    - '[class*=''ProductListing_wrapper'']'
    - '[class*=''Standard_bottom-utils'']'
    - .PageUtils_container-top__pyYDD
    - .PageUtils_container-left__whOYQ
    - .TranslateMessage_translate-message__iUF3m
    - .ecommerce-module
    - '#lp-article-tout'
    - .Standard_right-rail__tTaUI
    - .Standard_author__Ke782
    cleanup_rules:
      stop_at_repeated_links: true
      max_consecutive_links: 3
  title:
    og_meta: og:title
    fallback_selector: h1.article-header__title
  author:
    json_ld: author.name
    fallback_selector: span.byline-name
  date_published:
    json_ld: datePublished
    fallback_selector: time.article-meta__date
notes: 'HBR articles typically have their main content within an <article> tag, often
  nested inside a specific div like ''.article-body__content''.

  The exclusion list is aggressive, targeting common patterns for social sharing,
  related articles, ads, author bios (if positioned post-content), and newsletter
  sign-ups. Specific HBR classes like ''.article-actions'' and ''.about-the-author-section''
  are included for precise removal.

  Cleanup rules for repeated links help prevent extraction of "More Articles" or similar
  list-based navigation at the end.'
requires_browser: true
learned_at: '2025-10-02T19:23:11.083960'
