domain: forentrepreneurs.com
extraction:
  article_content:
    selector: body
    exclude_selectors:
    - .top-search-results
    - '[data-id=''18aacc1'']'
    - '[data-id=''61df0781'']'
    - .elementor-widget-breadcrumbs
    - section.elementor-element-b5297af
    - '[data-widget_type=''jet-listing-grid.default'']'
    - div.stay-updated
    - '[data-widget_type=''post-comments.theme_comments'']'
    - '[data-id=''dc6219b'']'
    - div.copyright
    - .skip-link
notes: 'Inverted learning approach. Validation: ok'
learned_at: '2025-10-05T16:34:05.053417'
