domain: forentrepreneurs.com
extraction:
  article_content:
    selector: div[class*='elementor'][class*='post']
    fallback: body
    exclude_selectors:
    - nav
    - header
    - footer
    - '[class*="share"]'
    - '[class*="social"]'
    - '[class*="recommended"]'
    - '[class*="related"]'
    - '[class*="ad"]'
    - '[class*="promo"]'
    - .elementor-section[class*="header"]
    - .elementor-section[class*="footer"]
    - .elementor-section[class*="sidebar"]
    - .elementor-section[class*="navigation"]
    cleanup_rules:
      stop_at_repeated_links: true
      max_consecutive_links: 3
  title:
    og_meta: og:title
    fallback_selector: h1
  author:
    json_ld: author.name
    fallback_selector: .author, [itemprop="author"]
  date_published:
    json_ld: datePublished
    fallback_selector: time[datetime], .date, .published-date
notes: 'Fallback config created using selector: div[class*=''elementor''][class*=''post'']'
learned_at: '2025-10-03T16:33:10.028902'
