domain: hbr.org
extraction:
  article_content:
    selector: body
    exclude_selectors:
    - a.SkipLink_skip-link__u3yKj
    - header[class*='Header-module_header']
    - nav[class*='MegaMenu-module_mega-menu']
    - span[class*='StandardHeadline_headline-topic']
    - ul[class*='PageUtils_container']
    - div[class*='ArticlePromo_standard']
    - div[class*='LPArticleTout_container']
    - div[class*='RecommendedForYou_container']
    - div.ecommerce-module
    - div[class*='RelatedTopics_container']
    - div[class*='Footer-module_subscribe-link-container']
    - button.Summary_button__t98CR
    - section[class*='PartnerCenter-module_container']
    - div[data-testid="ad-container"]
    - footer.Footer-module_footer__smP7p
    - div[class*='TranslateMessage_translate-message']
notes: 'Inverted learning approach. Validation: ok'
requires_browser: true
learned_at: '2025-10-05T17:55:44.689461'
