domain: renascence.io
extraction:
  article_content:
    selector: header.section_blog-post_body
    exclude_selectors:
    - .navbar5_component
    - .navbar5_blog-list-wrapper
    - .blog-post_body_social-links-wrapper
    - .blog-post_body_author-wrapper
    - .section_customer-experience-management-consulting-services_3_layout
    - .section_blog-post_newsletter
    - .footer6_component
    - .industries_8_customer-experience-podcasts_featured-list-wrapper
    - .industries_8_customer-experience-podcasts_list-wrapper
    - .div-block-13
    - .blog-post_body_tags-wrapper
    truncate_after: section.section_customer-experience-management-consulting-services_3_layout
notes: 'Inverted learning approach. Boundaries: yes. Validation: needs_fixes'
learned_at: '2025-10-05T19:20:46.007392'
